(() => {
  'use strict';
  if (!document.body.classList.contains('reconciliation-page')) return;
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;

  const revealObserver = 'IntersectionObserver' in window ? new IntersectionObserver(entries => entries.forEach(entry => {
    if (entry.isIntersecting) { entry.target.classList.add('visible'); revealObserver.unobserve(entry.target); }
  }), { threshold: .08 }) : null;
  $$('.reveal').forEach(el => revealObserver ? revealObserver.observe(el) : el.classList.add('visible'));

  const stages = {
    connect: { title: 'Five sources, one controlled intake', badge: '5 sources connected', body: `<div class="source-grid"><article><small>PAYMENT PROCESSOR</small><b>Gross sales · $48,600</b><span>Connected</span></article><article><small>BANK</small><b>Deposit · $45,042</b><span>Connected</span></article><article><small>ERP</small><b>Sales · $48,600</b><span>Connected</span></article><article><small>REFUND REPORT</small><b>Refunds · $2,100</b><span>Connected</span></article><article><small>FEE REPORT</small><b>Fees · $1,458</b><span>Connected</span></article></div><div class="stage-ledger"><div><span>Records collected</span><strong>1,842 transactions</strong></div><div><span>Source lineage</span><strong class="success">Attached</strong></div><div><span>Collection status</span><strong class="success">Complete</strong></div></div>` },
    normalise: { title: 'Different records become comparable', badge: 'Shared schema ready', body: `<div class="transform-list"><div><span>10/14/26 · 14 Oct</span><i>→</i><b>2026-10-14</b></div><div><span>48,600 USD · $48600</span><i>→</i><b>USD 48,600.00</b></div><div><span>TX_ 884-21</span><i>→</i><b>TX88421</b></div><div><span>THEORREM SHOP LLC</span><i>→</i><b>Theorrem Shop</b></div><div><span>Negative sale entries</span><i>→</i><b>Refunds</b></div><div><span>Processor deduction</span><i>→</i><b>Processing fee</b></div></div><div class="match-banner">✓ Dates, currencies, IDs, entities and record classes now share one format</div>` },
    match: { title: 'The settlement resolves to the bank deposit', badge: 'Complex match complete', body: `<div class="calculation"><div><span>Gross sales</span><b>$48,600</b></div><div><span>Minus refunds</span><b>− $2,100</b></div><div><span>Minus processing fees</span><b>− $1,458</b></div><div class="total"><span>Expected deposit</span><b>$45,042</b></div><div><span>Actual bank deposit</span><b>$45,042</b></div></div><div class="match-banner">✓ 1,842 processor records matched to one bank settlement</div>` },
    explain: { title: 'Every component of the difference is known', badge: 'No unresolved variance', body: `<div class="stage-ledger"><div><span>Deposit difference</span><strong class="success">$0</strong></div><div><span>Processor fee explained</span><strong>$1,458</strong></div><div><span>Refunds explained</span><strong>$2,100</strong></div><div><span>Unresolved settlement variance</span><strong class="success">None</strong></div></div><div class="match-banner">✓ The lower bank deposit is fully explained by valid refunds and fees</div>` },
    deliver: { title: 'The trusted result moves downstream', badge: 'Reconciled', body: `<div class="delivery-list"><div><span>Fee journal sent to ERP</span><b>Delivered ✓</b></div><div><span>Settlement marked reconciled</span><b>Complete ✓</b></div><div><span>Source records attached</span><b>Retained ✓</b></div><div><span>Activity history retained</span><b>Auditable ✓</b></div><div><span>Analytics updated</span><b>Published ✓</b></div></div>` }
  };
  const stage = $('#workflowStage');
  const workflowButtons = $$('.workflow-tabs button');
  let workflowIndex = 0, workflowTimer;
  function setWorkflow(key, manual = false) {
    const data = stages[key]; if (!data || !stage) return;
    workflowIndex = workflowButtons.findIndex(b => b.dataset.step === key);
    workflowButtons.forEach((b, i) => { const active = i === workflowIndex; b.classList.toggle('active', active); b.setAttribute('aria-selected', String(active)); b.setAttribute('tabindex', active ? '0' : '-1'); });
    stage.innerHTML = `<div class="stage-head"><div><small>SETTLEMENT WORKFLOW</small><h3>${data.title}</h3></div><span>${data.badge}</span></div>${data.body}`;
    if (manual) startWorkflowTimer();
  }
  function startWorkflowTimer() { clearInterval(workflowTimer); if (!reduced) workflowTimer = setInterval(() => setWorkflow(workflowButtons[(workflowIndex + 1) % workflowButtons.length].dataset.step), 5000); }
  workflowButtons.forEach(b => b.addEventListener('click', () => setWorkflow(b.dataset.step, true)));
  setWorkflow('connect');
  const workflowBoard = $('[data-tabs="workflow"]');
  if ('IntersectionObserver' in window && workflowBoard) new IntersectionObserver(([entry]) => entry.isIntersecting ? startWorkflowTimer() : clearInterval(workflowTimer), { threshold: .2 }).observe(workflowBoard); else startWorkflowTimer();

  $('.accept-case')?.addEventListener('click', e => { e.currentTarget.textContent = 'Recommendation accepted'; e.currentTarget.disabled = true; $('.accepted-result')?.classList.add('visible'); });

  const usecases = [
    { id:'ap', tab:'AP three-way matching', title:'Clear routine invoices. Quantify the exceptions.', sources:[['Purchase order','PO-8821 · 300 units'],['Goods receipt','GRN-4418 · 270 units'],['Supplier invoice','INV-3391 · $54,000']], checks:['Quantity','Unit price','Tax','Vendor','PO reference'], results:[['Matched value','$48,600 approved'],['Exception','30 units · $5,400'],['Destination','ERP + reviewer queue']], outcome:'Routine invoices cleared automatically. Quantity and price conflicts routed with calculated exposure.' },
    { id:'bank', tab:'Bank vs ledger', title:'Explain the bank before close.', sources:[['Bank statement','Deposit · $45,042'],['General ledger','Settlement · $46,500'],['Payment records','1,842 transactions'],['Fee report','Fees · $1,458']], checks:['Amount','Date','Reference','Counterparty','Currency'], results:[['Timing difference','$0'],['Unposted fee','$1,458 identified'],['Result','Ledger correction ready']], outcome:'Unposted fees, timing differences and missing entries identified before close.' },
    { id:'cash', tab:'Customer payment application', title:'Apply payments without perfect references.', sources:[['Bank payment','ACME DIST. · $18,420'],['Open invoices','1048 + 1071'],['Remittance email','Two invoices mentioned'],['Customer account','Acme Distribution']], checks:['Customer identity','Invoice references','Combined amounts','Payment date','Competing matches'], results:[['Suggested match','97% confidence'],['Invoices','1048 + 1071 cleared'],['Destination','Customer balance updated']], outcome:'Payments applied to the correct invoices even when references are incomplete.' },
    { id:'settlement', tab:'Payment settlement', title:'Tie every payout to its transactions.', sources:[['Payment processor','Gross · $48,600'],['Bank deposit','$45,042'],['Refund report','$2,100'],['Fee report','$1,458'],['ERP','Fee not posted']], checks:['Gross sales','Fees','Refunds','Chargebacks','FX','Settlement timing'], results:[['Expected deposit','$45,042'],['Variance','$0 explained'],['Destination','Fee journal + ERP']], outcome:'Every settlement explained down to its transactions.' },
    { id:'delivery', tab:'Order vs shipment vs delivery', title:'Know what was ordered, moved and received.', sources:[['Customer order','ORD-480 · 120 units'],['Warehouse dispatch','118 units sent'],['Courier events','Two parcels'],['Delivery confirmation','116 units received']], checks:['SKU','Quantity','Customer','Dispatch status','Delivery status'], results:[['Short shipment','2 units'],['Delivery conflict','2 units'],['Result','Fulfilment case opened']], outcome:'Short shipments, missing deliveries and fulfilment conflicts surfaced automatically.' },
    { id:'marketplace', tab:'Marketplace payout', title:'Explain every fee, refund and payout.', sources:[['Marketplace orders','Gross · $31,400'],['Refunds','$1,800'],['Platform fees','$2,198'],['Chargebacks','$500'],['Bank payout','$26,902'],['ERP','Expected · $27,402']], checks:['Gross sales','Fees','Refunds','Chargebacks','Bank payout'], results:[['Missing record','Chargeback · $500'],['Corrected payout','$26,902'],['Result','Settlement reconciled']], outcome:'Marketplace payouts explained and tied back to individual orders.' },
    { id:'inventory', tab:'Inventory reconciliation', title:'See where stock differences began.', sources:[['ERP inventory','4,280 units'],['Warehouse system','4,264 units'],['Physical count','4,260 units'],['Transfers','12 in transit'],['Adjustments','8 damaged']], checks:['SKU','Location','Movement','Count date','Unit value'], results:[['In transit','12 classified'],['Damage','8 classified'],['Exception','4 units to review']], outcome:'Stock differences classified by location, movement and financial exposure.' },
    { id:'intercompany', tab:'Intercompany', title:'Align balances across entities and currencies.', sources:[['Entity A ledger','USD 84,200 receivable'],['Entity B ledger','EUR 77,100 payable'],['FX rates','Closing rate · 1.091'],['Intercompany invoices','12 records'],['Settlements','2 in transit']], checks:['Entity','Invoice','Currency','FX rate','Timing'], results:[['FX difference','$96 explained'],['In transit','2 payments'],['Result','Balances aligned']], outcome:'Intercompany balances aligned with currency and timing differences explained.' }
  ];
  const usecaseTabs = $('.usecase-tabs-recon'), usecasePanel = $('#reconUsecasePanel');
  if (usecaseTabs && usecasePanel) {
    usecaseTabs.innerHTML = usecases.map((u,i) => `<button type="button" data-usecase="${u.id}" class="${i?'':'active'}" role="tab">${u.tab}</button>`).join('');
    function setUsecase(id) { const u = usecases.find(x=>x.id===id) || usecases[0]; $$('.usecase-tabs-recon button').forEach(b=>{const active=b.dataset.usecase===u.id;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));}); usecasePanel.innerHTML=`<div class="uc-copy"><small>${u.tab.toUpperCase()}</small><h3>${u.title}</h3><p>Theorrem brings the relevant records into one controlled match.</p><h4>Checks performed</h4><div class="uc-tags">${u.checks.map(c=>`<span>${c}</span>`).join('')}</div><div class="uc-outcome"><b>Outcome</b><br>${u.outcome}</div></div><div class="uc-visual"><div class="uc-sources">${u.sources.map(s=>`<div class="uc-source"><small>SOURCE</small><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div><div class="uc-engine"><span>match</span><i>✓</i><span>explain</span></div><div class="uc-results">${u.results.map(r=>`<div class="uc-result"><small>RESULT</small><b>${r[0]}</b><span>${r[1]}</span></div>`).join('')}</div></div>`; }
    usecaseTabs.addEventListener('click',e=>{const b=e.target.closest('button');if(b)setUsecase(b.dataset.usecase)}); setUsecase('ap');
  }

  const modal = $('#reconcileModal'), demoBody = $('#reconcileDemoBody'), demoNext = $('#demoNext'), progress = $('.demo-progress');
  let demoStep = 0, previousFocus = null;
  const demoSteps = [
    { button:'Match records →', html:`<div class="demo-scene"><header><div><small>STEP 1 · COLLECT</small><h3>Three systems, one settlement</h3></div><span>Example data</span></header><div class="demo-records"><article class="demo-record"><small>MARKETPLACE REPORT</small><b>Expected payout · $27,402</b><dl><div><dt>Gross sales</dt><dd>$31,400</dd></div><div><dt>Refunds</dt><dd>− $1,800</dd></div><div><dt>Platform fees</dt><dd>− $2,198</dd></div></dl></article><article class="demo-record"><small>BANK</small><b>Actual deposit · $26,902</b><dl><div><dt>Date</dt><dd>15 Oct 2026</dd></div><div><dt>Reference</dt><dd>MP-SET-441</dd></div></dl></article><article class="demo-record"><small>ERP</small><b>Expected · $27,402</b><dl><div><dt>Chargeback</dt><dd>Not recorded</dd></div><div><dt>Status</dt><dd>Unreconciled</dd></div></dl></article></div></div>` },
    { button:'Open exception →', html:`<div class="demo-scene"><header><div><small>STEP 2 · MATCH</small><h3>Routine components matched</h3></div><span>Gross · refunds · fees</span></header><div class="demo-calculation"><div><span>Gross sales</span><b>$31,400</b></div><div><span>Minus refunds</span><b>− $1,800</b></div><div><span>Minus platform fees</span><b>− $2,198</b></div><div><span>Expected payout</span><b>$27,402</b></div><div><span>Bank deposit</span><b>$26,902</b></div></div><div class="demo-difference"><span>One unexplained difference remains</span><b>$500</b></div></div>` },
    { button:'Find related record →', html:`<div class="demo-scene"><header><div><small>STEP 3 · EXCEPTION</small><h3>$500 difference needs an explanation</h3></div><span>Source search ready</span></header><div class="demo-records"><article class="demo-record"><small>EXPECTED</small><b>$27,402</b><p>ERP and marketplace expected payout agree.</p></article><article class="demo-record"><small>ACTUAL</small><b>$26,902</b><p>Bank received $500 less than expected.</p></article><article class="demo-record"><small>UNRESOLVED</small><b style="color:#c84848">$500</b><p>No matching adjustment attached yet.</p></article></div><div class="demo-difference"><span>Theorrem can search related marketplace adjustments.</span><b>Review →</b></div></div>` },
    { button:'Accept explanation →', html:`<div class="demo-scene"><header><div><small>STEP 4 · EXPLAIN</small><h3>Missing chargeback record found</h3></div><span style="color:#16875d">98% confidence</span></header><div class="demo-calculation"><div><span>Expected payout</span><b>$27,402</b></div><div class="correction"><span>Marketplace chargeback</span><b>− $500</b></div><div><span>Corrected payout</span><b>$26,902</b></div><div class="total"><span>Bank deposit</span><b>$26,902 · Matched</b></div></div><div class="match-banner">Why this matched: settlement ID, amount, merchant entity and posting window aligned.</div></div>` },
    { button:'Generate ERP adjustment →', html:`<div class="demo-scene"><header><div><small>STEP 5 · RESOLVE</small><h3>Explanation accepted</h3></div><span>Human decision retained</span></header><div class="demo-success"><i>✓</i><h3>Chargeback attached to settlement</h3><p>The $500 adjustment now explains the difference between the expected and actual payout.</p></div><div class="lineage"><span>Marketplace report</span><span>Bank deposit</span><span>ERP record</span><span>Chargeback adjustment</span><span>Approval recorded</span></div></div>` },
    { button:'Deliver correction →', html:`<div class="demo-scene"><header><div><small>STEP 6 · DELIVER</small><h3>ERP adjustment is ready</h3></div><span>Journal preview</span></header><div class="demo-calculation"><div><span>Journal type</span><b>Marketplace chargeback</b></div><div><span>Settlement reference</span><b>MP-SET-441</b></div><div><span>Adjustment amount</span><b>$500</b></div><div><span>Destination</span><b>ERP · Payments clearing</b></div></div><div class="match-banner">Source lineage and full activity history will remain attached after delivery.</div></div>` },
    { button:'View reconciled result →', html:`<div class="demo-scene"><header><div><small>STEP 7 · COMPLETE</small><h3>Correction delivered</h3></div><span style="color:#16875d">ERP updated</span></header><div class="demo-success"><i>↗</i><h3>$500 adjustment delivered downstream</h3><p>Expected payout, chargeback and bank deposit now agree.</p></div><div class="lineage"><span>ERP journal generated</span><span>Reviewer action retained</span><span>Sources attached</span><span>Activity history visible</span></div></div>` },
    { button:'Close workflow', html:`<div class="demo-scene"><header><div><small>ILLUSTRATIVE RESULT</small><h3>Settlement reconciled</h3></div><span style="color:#16875d">Complete</span></header><div class="demo-success"><i>✓</i><h3>$26,902 trusted payout</h3><p>Gross sales, refunds, fees and the missing chargeback all connect to the bank deposit and corrected ERP record.</p></div><div class="lineage"><span>Marketplace → $31,400</span><span>Refunds → $1,800</span><span>Fees → $2,198</span><span>Chargeback → $500</span><span>Bank → $26,902</span></div></div>` }
  ];
  function renderDemo(){ const s=demoSteps[demoStep]; demoBody.innerHTML=s.html; demoNext.textContent=s.button; progress?.style.setProperty('--progress',`${((demoStep+1)/demoSteps.length)*100}%`); }
  function openDemo(e){ previousFocus=e?.currentTarget||document.activeElement;demoStep=0;modal.hidden=false;document.body.classList.add('modal-open');renderDemo();setTimeout(()=>$('.modal-close')?.focus(),0); }
  function closeDemo(){modal.hidden=true;document.body.classList.remove('modal-open');previousFocus?.focus();}
  $$('.js-open-reconcile').forEach(b=>b.addEventListener('click',openDemo)); $$('[data-close-modal]').forEach(b=>b.addEventListener('click',closeDemo));
  demoNext?.addEventListener('click',()=>{if(demoStep===demoSteps.length-1)closeDemo();else{demoStep++;renderDemo();}});
  $('#demoSource')?.addEventListener('click',e=>toast(e.currentTarget,'Source lineage is visible throughout the workflow.'));
  $('#demoComment')?.addEventListener('click',e=>toast(e.currentTarget,'Comment added to the activity history.'));
  function toast(anchor,text){$('.source-toast')?.remove();const el=document.createElement('span');el.className='source-toast';el.textContent=text;anchor.closest('.reconcile-dialog').append(el);setTimeout(()=>el.remove(),2200)}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeDemo();if(e.key==='Tab'&&!modal.hidden){const focusable=$$('button,a[href]',modal).filter(x=>!x.disabled);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
})();
